### ISSUE TITLE
I can't close the panel?

### ISSUE THREAD

**Issue by piejanssens** [fstiewitz/regex-tester#2]
I go to "Packages>Regex Tester>Toggle" but this just highlights the "Regular Expression" input field of the panel instead of closing it when it's open. 
Can you add an 'x' (close) button to the panel?

**Comment by silpheel** [comment]
This should be solved in 0.2.2: There is a Hide command, and the Esc key would do the same.

**Comment by fstiewitz** [comment]
There is still no close button though. The next step is refactoring the UI.
